[2025-07-25T21:34:59.082+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T21:34:59.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sigtap_00_installation.executar_schema_no_banco manual__2025-07-25T21:34:53.396548+00:00 [queued]>
[2025-07-25T21:34:59.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sigtap_00_installation.executar_schema_no_banco manual__2025-07-25T21:34:53.396548+00:00 [queued]>
[2025-07-25T21:34:59.112+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-25T21:34:59.123+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): executar_schema_no_banco> on 2025-07-25 21:34:53.396548+00:00
[2025-07-25T21:34:59.130+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-25T21:34:59.131+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2025-07-25T21:34:59.131+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sigtap_00_installation', 'executar_schema_no_banco', 'manual__2025-07-25T21:34:53.396548+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sigtap_00_installation_dag.py', '--cfg-path', '/tmp/tmpmyhdbrga']
[2025-07-25T21:34:59.132+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask executar_schema_no_banco
[2025-07-25T21:34:59.183+0000] {task_command.py:426} INFO - Running <TaskInstance: sigtap_00_installation.executar_schema_no_banco manual__2025-07-25T21:34:53.396548+00:00 [running]> on host 012b9571e725
[2025-07-25T21:34:59.260+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sigtap_00_installation' AIRFLOW_CTX_TASK_ID='executar_schema_no_banco' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T21:34:53.396548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T21:34:53.396548+00:00'
[2025-07-25T21:34:59.261+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T21:34:59.271+0000] {subprocess.py:63} INFO - Tmp dir *** location: /tmp
[2025-07-25T21:34:59.273+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/src/step_02_create_table_sigtap.py']
[2025-07-25T21:34:59.284+0000] {subprocess.py:86} INFO - Output:
[2025-07-25T21:34:59.449+0000] {subprocess.py:93} INFO - --- INICIANDO ETAPA 02: CRIAÇÃO DAS TABELAS SIGTAP ---
[2025-07-25T21:34:59.449+0000] {subprocess.py:93} INFO - Arquivo de configuração lido com sucesso.
[2025-07-25T21:34:59.450+0000] {subprocess.py:93} INFO - ERRO: O diretório de scripts SQL não foi encontrado em: /opt/airflow/create_db
[2025-07-25T21:34:59.456+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-25T21:34:59.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T21:34:59.467+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-25T21:34:59.471+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sigtap_00_installation, task_id=executar_schema_no_banco, run_id=manual__2025-07-25T21:34:53.396548+00:00, execution_date=20250725T213453, start_date=20250725T213459, end_date=20250725T213459
[2025-07-25T21:34:59.483+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task executar_schema_no_banco (Bash command failed. The command returned a non-zero exit code 1.; 63)
[2025-07-25T21:34:59.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T21:34:59.520+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T21:34:59.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
